In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data_base = pd.read_csv("/content/Inventory Management E-Grocery - InventoryData.csv")

In [ ]:
data_base.head(5)

,SKU_ID,SKU_Name,Category,ABC_Class,Supplier_ID,Supplier_Name,Warehouse_ID,Warehouse_Location,Batch_ID,Received_Date,...,SKU_Churn_Rate,Order_Frequency_per_month,Supplier_OnTime_Pct,FIFO_FEFO,Inventory_Status,Count_Variance,Audit_Date,Audit_Variance_Pct,Demand_Forecast_Accuracy_Pct,Notes
0,SKU0001,Pantry Product 13,Pantry,A,S005,PT Agro Raya,WHBDG,Bandung - Rancaekek,BATCH2679,2025-07-14,...,"2,39","5,00","70,68%",FIFO,In Stock,0,2025-06-26,"-7,14%","95,67%",NaN
1,SKU0002,Fresh Product 112,Fresh Produce,C,S004,PT Nusantara Supplier,WHDPS,Denpasar - Tabanan,BATCH4257,2025-04-08,...,"3,34","12,00","84,61%",FEFO,Low Stock,4,2025-08-12,"2,15%","86,00%",NaN
2,SKU0003,Meat Product 446,Meat,B,S001,PT Segar Makmur,WHBDG,Bandung - Rancaekek,BATCH6574,2025-03-15,...,"2,26","11,00","85,36%",FIFO,Expiring Soon,-5,2025-08-13,"6,85%","87,64%",NaN
3,SKU0004,Seafood Product 48,Seafood,A,S007,PT Bakerindo,WHJKT,Jakarta - Cengkareng,BATCH5333,2025-06-10,...,"2,72","10,00","72,81%",FIFO,Expiring Soon,0,2025-07-13,"-6,69%","71,15%",NaN
4,SKU0005,Personal Product 194,Personal Care,A,S002,PT Indo Fresh,WHDPS,Denpasar - Tabanan,BATCH6925,2025-06-26,...,"2,18","2,00","70,93%",FIFO,In Stock,-5,2025-06-11,"1,23%","76,25%",High return rate

## **DATA CLEANING**

In [ ]:
data_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   SKU_ID                        1000 non-null   object
 1   SKU_Name                      1000 non-null   object
 2   Category                      1000 non-null   object
 3   ABC_Class                     1000 non-null   object
 4   Supplier_ID                   1000 non-null   object
 5   Supplier_Name                 1000 non-null   object
 6   Warehouse_ID                  1000 non-null   object
 7   Warehouse_Location            1000 non-null   object
 8   Batch_ID                      1000 non-null   object
 9   Received_Date                 1000 non-null   object
 10  Last_Purchase_Date            1000 non-null   object
 11  Expiry_Date                   1000 non-null   object
 12  Stock_Age_Days                1000 non-null   int64
 13  Quantity_On_Hand              1000 non-null   int64
 14  Quantity_Reserved             1000 non-null   int64
 15  Quantity_Committed            1000 non-null   int64
 16  Damaged_Qty                   1000 non-null   int64
 17  Returns_Qty                   1000 non-null   int64
 18  Avg_Daily_Sales               1000 non-null   object
 19  Forecast_Next_30d             1000 non-null   float64
 20  Days_of_Inventory             1000 non-null   object
 21  Reorder_Point                 1000 non-null   float64
 22  Safety_Stock                  1000 non-null   int64
 23  Lead_Time_Days                1000 non-null   int64
 24  Unit_Cost_USD                 1000 non-null   object
 25  Last_Purchase_Price_USD       1000 non-null   object
 26  Total_Inventory_Value_USD     1000 non-null   object
 27  SKU_Churn_Rate                1000 non-null   object
 28  Order_Frequency_per_month     1000 non-null   object
 29  Supplier_OnTime_Pct           1000 non-null   object
 30  FIFO_FEFO                     1000 non-null   object
 31  Inventory_Status              1000 non-null   object
 32  Count_Variance                1000 non-null   int64
 33  Audit_Date                    1000 non-null   object
 34  Audit_Variance_Pct            1000 non-null   object
 35  Demand_Forecast_Accuracy_Pct  1000 non-null   object
 36  Notes                         166 non-null    object
dtypes: float64(2), int64(9), object(26)
memory usage: 289.2+ KB

In [ ]:
# the count of empty values
data_base.isnull().sum()

SKU_ID                            0
SKU_Name                          0
Category                          0
ABC_Class                         0
Supplier_ID                       0
Supplier_Name                     0
Warehouse_ID                      0
Warehouse_Location                0
Batch_ID                          0
Received_Date                     0
Last_Purchase_Date                0
Expiry_Date                       0
Stock_Age_Days                    0
Quantity_On_Hand                  0
Quantity_Reserved                 0
Quantity_Committed                0
Damaged_Qty                       0
Returns_Qty                       0
Avg_Daily_Sales                   0
Forecast_Next_30d                 0
Days_of_Inventory                 0
Reorder_Point                     0
Safety_Stock                      0
Lead_Time_Days                    0
Unit_Cost_USD                     0
Last_Purchase_Price_USD           0
Total_Inventory_Value_USD         0
SKU_Churn_Rate                    0
Order_Frequency_per_month         0
Supplier_OnTime_Pct               0
FIFO_FEFO                         0
Inventory_Status                  0
Count_Variance                    0
Audit_Date                        0
Audit_Variance_Pct                0
Demand_Forecast_Accuracy_Pct      0
Notes                           834
dtype: int64

In [ ]:
print("Shape:", data_base.shape)

Shape: (1000, 37)

In [ ]:
print("\nColumns:")
for i, col in enumerate(data_base.columns, 1):
    print(i, col)

Columns:
1 SKU_ID
2 SKU_Name
3 Category
4 ABC_Class
5 Supplier_ID
6 Supplier_Name
7 Warehouse_ID
8 Warehouse_Location
9 Batch_ID
10 Received_Date
11 Last_Purchase_Date
12 Expiry_Date
13 Stock_Age_Days
14 Quantity_On_Hand
15 Quantity_Reserved
16 Quantity_Committed
17 Damaged_Qty
18 Returns_Qty
19 Avg_Daily_Sales
20 Forecast_Next_30d
21 Days_of_Inventory
22 Reorder_Point
23 Safety_Stock
24 Lead_Time_Days
25 Unit_Cost_USD
26 Last_Purchase_Price_USD
27 Total_Inventory_Value_USD
28 SKU_Churn_Rate
29 Order_Frequency_per_month
30 Supplier_OnTime_Pct
31 FIFO_FEFO
32 Inventory_Status
33 Count_Variance
34 Audit_Date
35 Audit_Variance_Pct
36 Demand_Forecast_Accuracy_Pct
37 Notes

In [ ]:
object_cols = data_base.select_dtypes(include='object').columns

for col in object_cols:
    print(f"\n===== {col} =====")
    print(data_base[col].head(5).tolist())

===== SKU_ID =====
['SKU0001', 'SKU0002', 'SKU0003', 'SKU0004', 'SKU0005']

===== SKU_Name =====
['Pantry Product 13', 'Fresh Product 112', 'Meat Product 446', 'Seafood Product 48', 'Personal Product 194']

===== Category =====
['Pantry', 'Fresh Produce', 'Meat', 'Seafood', 'Personal Care']

===== ABC_Class =====
['A', 'C', 'B', 'A', 'A']

===== Supplier_ID =====
['S005', 'S004', 'S001', 'S007', 'S002']

===== Supplier_Name =====
['PT Agro Raya', 'PT Nusantara Supplier', 'PT Segar Makmur', 'PT Bakerindo', 'PT Indo Fresh']

===== Warehouse_ID =====
['WHBDG', 'WHDPS', 'WHBDG', 'WHJKT', 'WHDPS']

===== Warehouse_Location =====
['Bandung - Rancaekek', 'Denpasar - Tabanan', 'Bandung - Rancaekek', 'Jakarta - Cengkareng', 'Denpasar - Tabanan']

===== Batch_ID =====
['BATCH2679', 'BATCH4257', 'BATCH6574', 'BATCH5333', 'BATCH6925']

===== Received_Date =====
['2025-07-14', '2025-04-08', '2025-03-15', '2025-06-10', '2025-06-26']

===== Last_Purchase_Date =====
['2025-06-01', '2025-02-22', '2025-02-26', '2025-04-20', '2025-05-21']

===== Expiry_Date =====
['2027-04-25', '2025-04-11', '2025-04-02', '2025-06-18', '2030-01-03']

===== Avg_Daily_Sales =====
['28,57', '34,99', '36,55', '25,49', '17,05']

===== Days_of_Inventory =====
['12,57', '8,97', '13,27', '11,02', '13,78']

===== Unit_Cost_USD =====
['$5,81', '$1,45', '$1,86', '$14,50', '$9,46']

===== Last_Purchase_Price_USD =====
['$5,71', '$1,33', '$1,69', '$14,12', '$10,31']

===== Total_Inventory_Value_USD =====
['$2.084,25', '$456,71', '$902,63', '$4.073,15', '$2.222,91']

===== SKU_Churn_Rate =====
['2,39', '3,34', '2,26', '2,72', '2,18']

===== Order_Frequency_per_month =====
['5,00', '12,00', '11,00', '10,00', '2,00']

===== Supplier_OnTime_Pct =====
['70,68%', '84,61%', '85,36%', '72,81%', '70,93%']

===== FIFO_FEFO =====
['FIFO', 'FEFO', 'FIFO', 'FIFO', 'FIFO']

===== Inventory_Status =====
['In Stock', 'Low Stock', 'Expiring Soon', 'Expiring Soon', 'In Stock']

===== Audit_Date =====
['2025-06-26', '2025-08-12', '2025-08-13', '2025-07-13', '2025-06-11']

===== Audit_Variance_Pct =====
['-7,14%', '2,15%', '6,85%', '-6,69%', '1,23%']

===== Demand_Forecast_Accuracy_Pct =====
['95,67%', '86,00%', '87,64%', '71,15%', '76,25%']

===== Notes =====
[nan, nan, nan, nan, 'High return rate']

In [ ]:
categorical_cols = [
    'Category',
    'ABC_Class',
    'Supplier_Name',
    'Warehouse_ID',
    'Warehouse_Location',
    'FIFO_FEFO',
    'Inventory_Status'
]

for col in categorical_cols:
    print(f"\n===== {col} =====")
    print(data_base[col].value_counts())

===== Category =====
Category
Pantry           137
Personal Care    126
Beverages        120
Fresh Produce    110
Household        103
Dairy             96
Meat              87
Frozen            86
Bakery            69
Seafood           66
Name: count, dtype: int64

===== ABC_Class =====
ABC_Class
C    500
B    300
A    200
Name: count, dtype: int64

===== Supplier_Name =====
Supplier_Name
PT Indo Fresh            125
PT Bakerindo             113
PT Hygienic Supplies     110
PT Beverage Nusantara    104
PT Frozen Express         98
PT Agro Raya              96
PT Segar Makmur           91
PT Nusantara Supplier     89
PT Prima Distribusi       89
PT DailyDairy             85
Name: count, dtype: int64

===== Warehouse_ID =====
Warehouse_ID
WHBDG    220
WHDPS    220
WHSBY    198
WHMDN    189
WHJKT    173
Name: count, dtype: int64

===== Warehouse_Location =====
Warehouse_Location
Bandung - Rancaekek     220
Denpasar - Tabanan      220
Surabaya - Sidoarjo     198
Medan - Deli Serdang    189
Jakarta - Cengkareng    173
Name: count, dtype: int64

===== FIFO_FEFO =====
FIFO_FEFO
FIFO    516
FEFO    484
Name: count, dtype: int64

===== Inventory_Status =====
Inventory_Status
In Stock         428
Expiring Soon    329
Low Stock        241
Out of Stock       2
Name: count, dtype: int64

In [ ]:
data_dictionary = pd.DataFrame({
    'Column': data_base.columns,
    'Data_Type': data_base.dtypes.astype(str).values,
    'Non_Null': data_base.notna().sum().values,
    'Unique_Values': data_base.nunique().values
})

data_dictionary

                          Column Data_Type  Non_Null  Unique_Values
0                         SKU_ID    object      1000           1000
1                       SKU_Name    object      1000            900
2                       Category    object      1000             10
3                      ABC_Class    object      1000              3
4                    Supplier_ID    object      1000             10
5                  Supplier_Name    object      1000             10
6                   Warehouse_ID    object      1000              5
7             Warehouse_Location    object      1000              5
8                       Batch_ID    object      1000            923
9                  Received_Date    object      1000            179
10            Last_Purchase_Date    object      1000            221
11                   Expiry_Date    object      1000            646
12                Stock_Age_Days     int64      1000            179
13              Quantity_On_Hand     int64      1000            472
14             Quantity_Reserved     int64      1000            182
15            Quantity_Committed     int64      1000            152
16                   Damaged_Qty     int64      1000              8
17                   Returns_Qty     int64      1000              5
18               Avg_Daily_Sales    object      1000            912
19             Forecast_Next_30d   float64      1000            774
20             Days_of_Inventory    object      1000            698
21                 Reorder_Point   float64      1000            374
22                  Safety_Stock     int64      1000            198
23                Lead_Time_Days     int64      1000              8
24                 Unit_Cost_USD    object      1000            700
25       Last_Purchase_Price_USD    object      1000            710
26     Total_Inventory_Value_USD    object      1000            996
27                SKU_Churn_Rate    object      1000            425
28     Order_Frequency_per_month    object      1000             39
29           Supplier_OnTime_Pct    object      1000            848
30                     FIFO_FEFO    object      1000              2
31              Inventory_Status    object      1000              4
32                Count_Variance     int64      1000             17
33                    Audit_Date    object      1000             91
34            Audit_Variance_Pct    object      1000            787
35  Demand_Forecast_Accuracy_Pct    object      1000            887
36                         Notes    object       166              5

In [ ]:
data_base.dtypes

SKU_ID                           object
SKU_Name                         object
Category                         object
ABC_Class                        object
Supplier_ID                      object
Supplier_Name                    object
Warehouse_ID                     object
Warehouse_Location               object
Batch_ID                         object
Received_Date                    object
Last_Purchase_Date               object
Expiry_Date                      object
Stock_Age_Days                    int64
Quantity_On_Hand                  int64
Quantity_Reserved                 int64
Quantity_Committed                int64
Damaged_Qty                       int64
Returns_Qty                       int64
Avg_Daily_Sales                  object
Forecast_Next_30d               float64
Days_of_Inventory                object
Reorder_Point                   float64
Safety_Stock                      int64
Lead_Time_Days                    int64
Unit_Cost_USD                    object
Last_Purchase_Price_USD          object
Total_Inventory_Value_USD        object
SKU_Churn_Rate                   object
Order_Frequency_per_month        object
Supplier_OnTime_Pct              object
FIFO_FEFO                        object
Inventory_Status                 object
Count_Variance                    int64
Audit_Date                       object
Audit_Variance_Pct               object
Demand_Forecast_Accuracy_Pct     object
Notes                            object
dtype: object

In [ ]:
data_clean = data_base.copy()

In [ ]:
numeric_comma_cols = [
    'Avg_Daily_Sales',
    'Days_of_Inventory',
    'SKU_Churn_Rate',
    'Order_Frequency_per_month'
]

for col in numeric_comma_cols:
    data_clean[col] = (
        data_clean[col].astype(str)  # Explicitly convert to string type
        .str.replace('.', '', regex=False)  # Remove thousands separator
        .str.replace(',', '.', regex=False)  # Replace decimal comma with period
        .astype(float)
    )

In [ ]:
currency_cols = [
    'Unit_Cost_USD',
    'Last_Purchase_Price_USD',
    'Total_Inventory_Value_USD'
]

for col in currency_cols:
    data_clean[col] = (
        data_clean[col]
        .str.replace('$', '', regex=False)
        .str.replace('.', '', regex=False)
        .str.replace(',', '.', regex=False)
        .astype(float)
    )

In [ ]:
percentage_cols = [
    'Supplier_OnTime_Pct',
    'Audit_Variance_Pct',
    'Demand_Forecast_Accuracy_Pct'
]

for col in percentage_cols:
    data_clean[col] = (
        data_clean[col]
        .str.replace('%', '', regex=False)
        .str.replace(',', '.', regex=False)
        .astype(float)
    )

In [ ]:
data_clean.dtypes

SKU_ID                           object
SKU_Name                         object
Category                         object
ABC_Class                        object
Supplier_ID                      object
Supplier_Name                    object
Warehouse_ID                     object
Warehouse_Location               object
Batch_ID                         object
Received_Date                    object
Last_Purchase_Date               object
Expiry_Date                      object
Stock_Age_Days                    int64
Quantity_On_Hand                  int64
Quantity_Reserved                 int64
Quantity_Committed                int64
Damaged_Qty                       int64
Returns_Qty                       int64
Avg_Daily_Sales                 float64
Forecast_Next_30d               float64
Days_of_Inventory               float64
Reorder_Point                   float64
Safety_Stock                      int64
Lead_Time_Days                    int64
Unit_Cost_USD                   float64
Last_Purchase_Price_USD         float64
Total_Inventory_Value_USD       float64
SKU_Churn_Rate                  float64
Order_Frequency_per_month       float64
Supplier_OnTime_Pct             float64
FIFO_FEFO                        object
Inventory_Status                 object
Count_Variance                    int64
Audit_Date                       object
Audit_Variance_Pct              float64
Demand_Forecast_Accuracy_Pct    float64
Notes                            object
dtype: object

In [ ]:
numeric_cols = [
    'Stock_Age_Days',
    'Quantity_On_Hand',
    'Quantity_Reserved',
    'Quantity_Committed',
    'Damaged_Qty',
    'Returns_Qty',
    'Avg_Daily_Sales',
    'Forecast_Next_30d',
    'Days_of_Inventory',
    'Reorder_Point',
    'Safety_Stock',
    'Lead_Time_Days',
    'Unit_Cost_USD',
    'Last_Purchase_Price_USD',
    'Total_Inventory_Value_USD',
    'SKU_Churn_Rate',
    'Order_Frequency_per_month',
    'Supplier_OnTime_Pct',
    'Count_Variance',
    'Audit_Variance_Pct',
    'Demand_Forecast_Accuracy_Pct'
]

validation = data_clean[numeric_cols].describe().T

validation

,count,mean,std,min,25%,50%,75%,max
Stock_Age_Days,1000.0,91.541000,52.475308,0.000,46.00000,95.000,138.0000,180.00
Quantity_On_Hand,1000.0,231.563000,201.988781,0.000,81.00000,180.000,320.0000,977.00
Quantity_Reserved,1000.0,50.302000,50.106162,0.000,15.00000,35.000,68.0000,363.00
Quantity_Committed,1000.0,38.742000,42.765761,0.000,10.00000,24.000,53.0000,310.00
Damaged_Qty,1000.0,1.168000,1.295938,0.000,0.00000,1.000,2.0000,7.00
Returns_Qty,1000.0,0.812000,0.920600,0.000,0.00000,1.000,1.0000,4.00
Avg_Daily_Sales,1000.0,26.582790,21.248985,1.010,10.73250,20.225,36.5850,99.50
Forecast_Next_30d,1000.0,332.218940,301.358418,1.000,2.57725,288.000,572.5000,994.00
Days_of_Inventory,1000.0,9.993110,3.799894,0.000,7.42000,9.980,12.4825,21.95
Reorder_Point,1000.0,152.797633,163.056230,1.001,46.00000,98.000,196.0000,954.00
Safety_Stock,1000.0,58.473000,66.051556,2.000,19.00000,36.500,70.2500,624.00
Lead_Time_Days,1000.0,4.030000,2.983622,1.000,2.00000,3.000,5.0000,14.00
Unit_Cost_USD,1000.0,6.392590,5.385122,0.290,2.14750,4.660,8.8625,24.90
Last_Purchase_Price_USD,1000.0,6.540960,5.576295,0.290,2.24000,4.680,9.1600,26.59
Total_Inventory_Value_USD,1000.0,1259.530730,1312.495737,0.000,347.20750,802.180,1694.5850,11100.00
SKU_Churn_Rate,1000.0,6.329070,68.246388,1.370,2.40000,3.010,4.0400,2142.90
Order_Frequency_per_month,1000.0,9.813000,7.618929,1.000,4.00000,8.000,13.0000,46.00
Supplier_OnTime_Pct,1000.0,84.671890,8.461470,70.030,77.56000,84.785,92.1000,99.49
Count_Variance,1000.0,0.199000,2.708641,-7.000,-1.00000,0.000,2.0000,9.00
Audit_Variance_Pct,1000.0,0.012080,5.700840,-9.980,-4.94000,0.120,5.1575,9.95
Demand_Forecast_Accuracy_Pct,1000.0,78.970810,11.065562,60.010,70.06000,78.935,88.6225,97.96

In [ ]:
data_clean[numeric_cols].isna().sum()

Stock_Age_Days                  0
Quantity_On_Hand                0
Quantity_Reserved               0
Quantity_Committed              0
Damaged_Qty                     0
Returns_Qty                     0
Avg_Daily_Sales                 0
Forecast_Next_30d               0
Days_of_Inventory               0
Reorder_Point                   0
Safety_Stock                    0
Lead_Time_Days                  0
Unit_Cost_USD                   0
Last_Purchase_Price_USD         0
Total_Inventory_Value_USD       0
SKU_Churn_Rate                  0
Order_Frequency_per_month       0
Supplier_OnTime_Pct             0
Count_Variance                  0
Audit_Variance_Pct              0
Demand_Forecast_Accuracy_Pct    0
dtype: int64

In [ ]:
data_clean[
    ['Supplier_OnTime_Pct',
     'Audit_Variance_Pct',
     'Demand_Forecast_Accuracy_Pct']
].describe()

       Supplier_OnTime_Pct  Audit_Variance_Pct  Demand_Forecast_Accuracy_Pct
count           1000.00000          1000.00000                   1000.000000
mean              84.67189             0.01208                     78.970810
std                8.46147             5.70084                     11.065562
min               70.03000            -9.98000                     60.010000
25%               77.56000            -4.94000                     70.060000
50%               84.78500             0.12000                     78.935000
75%               92.10000             5.15750                     88.622500
max               99.49000             9.95000                     97.960000

In [ ]:
date_cols = [
    'Received_Date',
    'Last_Purchase_Date',
    'Expiry_Date',
    'Audit_Date'
]

for col in date_cols:
    data_clean[col] = pd.to_datetime(
        data_clean[col],
        errors='coerce'
    )

In [ ]:
data_clean.dtypes

SKU_ID                                  object
SKU_Name                                object
Category                                object
ABC_Class                               object
Supplier_ID                             object
Supplier_Name                           object
Warehouse_ID                            object
Warehouse_Location                      object
Batch_ID                                object
Received_Date                   datetime64[ns]
Last_Purchase_Date              datetime64[ns]
Expiry_Date                     datetime64[ns]
Stock_Age_Days                           int64
Quantity_On_Hand                         int64
Quantity_Reserved                        int64
Quantity_Committed                       int64
Damaged_Qty                              int64
Returns_Qty                              int64
Avg_Daily_Sales                        float64
Forecast_Next_30d                      float64
Days_of_Inventory                      float64
Reorder_Point                          float64
Safety_Stock                             int64
Lead_Time_Days                           int64
Unit_Cost_USD                          float64
Last_Purchase_Price_USD                float64
Total_Inventory_Value_USD              float64
SKU_Churn_Rate                         float64
Order_Frequency_per_month              float64
Supplier_OnTime_Pct                    float64
FIFO_FEFO                               object
Inventory_Status                        object
Count_Variance                           int64
Audit_Date                      datetime64[ns]
Audit_Variance_Pct                     float64
Demand_Forecast_Accuracy_Pct           float64
Notes                                   object
dtype: object

In [ ]:
data_clean[date_cols].head()

  Received_Date Last_Purchase_Date Expiry_Date Audit_Date
0    2025-07-14         2025-06-01  2027-04-25 2025-06-26
1    2025-04-08         2025-02-22  2025-04-11 2025-08-12
2    2025-03-15         2025-02-26  2025-04-02 2025-08-13
3    2025-06-10         2025-04-20  2025-06-18 2025-07-13
4    2025-06-26         2025-05-21  2030-01-03 2025-06-11

In [ ]:
print("Received > Expiry:",
      (data_clean['Received_Date'] > data_clean['Expiry_Date']).sum())

print("Last Purchase > Audit:",
      (data_clean['Last_Purchase_Date'] > data_clean['Audit_Date']).sum())

Received > Expiry: 0
Last Purchase > Audit: 115

## **FEATURE EXTRACTION**

In [ ]:
#ATP=Quantity_On_Hand−Quantity_Reserved−Quantity_Committed
data_clean['Available_to_Promise'] = (
    data_clean['Quantity_On_Hand']
    - data_clean['Quantity_Reserved']
    - data_clean['Quantity_Committed']
)

In [ ]:
data_clean[
    [
        'SKU_ID',
        'Quantity_On_Hand',
        'Quantity_Reserved',
        'Quantity_Committed',
        'Available_to_Promise'
    ]
].head(10)

,SKU_ID,Quantity_On_Hand,Quantity_Reserved,Quantity_Committed,Available_to_Promise
0,SKU0001,359,100,36,223
1,SKU0002,314,64,0,250
2,SKU0003,485,28,62,395
3,SKU0004,281,92,49,140
4,SKU0005,235,63,33,139
5,SKU0006,446,66,31,349
6,SKU0007,368,87,118,163
7,SKU0008,135,73,32,30
8,SKU0009,1,126,83,-208
9,SKU0010,49,12,16,21

In [ ]:
data_clean['Available_to_Promise'].describe()

count    1000.000000
mean      142.519000
std       168.255138
min      -672.000000
25%        36.000000
50%       105.000000
75%       211.250000
max       747.000000
Name: Available_to_Promise, dtype: float64

In [ ]:
print(
    "Negative ATP:",
    (data_clean['Available_to_Promise'] < 0).sum()
)

Negative ATP: 28

In [ ]:
data_clean['Forecast_Next_30d'] = data_base['Forecast_Next_30d']

In [ ]:
data_clean['Forecast_Daily_Demand'] = (
    data_clean['Forecast_Next_30d'] / 30
)

In [ ]:
data_clean['Forecast_Error'] = (
    data_clean['Forecast_Daily_Demand']
    - data_clean['Avg_Daily_Sales']
)

In [ ]:
data_clean['Forecast_Error_Pct'] = (
    data_clean['Forecast_Error']
    / data_clean['Avg_Daily_Sales']
) * 100

In [ ]:
data_clean[
    [
        'SKU_ID',
        'Avg_Daily_Sales',
        'Forecast_Next_30d',
        'Forecast_Daily_Demand',
        'Forecast_Error',
        'Forecast_Error_Pct'
    ]
].head(10)

,SKU_ID,Avg_Daily_Sales,Forecast_Next_30d,Forecast_Daily_Demand,Forecast_Error,Forecast_Error_Pct
0,SKU0001,28.57,971.000,32.366667,3.796667,13.288998
1,SKU0002,34.99,796.000,26.533333,-8.456667,-24.168810
2,SKU0003,36.55,1.377,0.045900,-36.504100,-99.874419
3,SKU0004,25.49,716.000,23.866667,-1.623333,-6.368511
4,SKU0005,17.05,518.000,17.266667,0.216667,1.270772
5,SKU0006,32.81,1.058,0.035267,-32.774733,-99.892512
6,SKU0007,53.35,1.521,0.050700,-53.299300,-99.904967
7,SKU0008,21.71,469.000,15.633333,-6.076667,-27.990173
8,SKU0009,78.76,1.975,0.065833,-78.694167,-99.916413
9,SKU0010,7.23,176.000,5.866667,-1.363333,-18.856616

In [ ]:
data_clean['Calculated_Inventory_Value'] = (
    data_clean['Quantity_On_Hand'] *
    data_clean['Unit_Cost_USD']
)

In [ ]:
data_clean['Inventory_Value_Difference'] = (
    data_clean['Total_Inventory_Value_USD']
    - data_clean['Calculated_Inventory_Value']
)

In [ ]:
data_clean[
    [
        'SKU_ID',
        'Quantity_On_Hand',
        'Unit_Cost_USD',
        'Total_Inventory_Value_USD',
        'Calculated_Inventory_Value',
        'Inventory_Value_Difference'
    ]
].head(10)

,SKU_ID,Quantity_On_Hand,Unit_Cost_USD,Total_Inventory_Value_USD,Calculated_Inventory_Value,Inventory_Value_Difference
0,SKU0001,359,5.81,2084.25,2085.79,-1.54
1,SKU0002,314,1.45,456.71,455.30,1.41
2,SKU0003,485,1.86,902.63,902.10,0.53
3,SKU0004,281,14.50,4073.15,4074.50,-1.35
4,SKU0005,235,9.46,2222.91,2223.10,-0.19
5,SKU0006,446,5.16,2303.14,2301.36,1.78
6,SKU0007,368,2.13,784.87,783.84,1.03
7,SKU0008,135,4.89,660.64,660.15,0.49
8,SKU0009,1,1.33,1562.93,1.33,1561.60
9,SKU0010,49,11.34,555.45,555.66,-0.21

In [ ]:
data_clean['Inventory_Value_Diff_Pct'] = (
    abs(data_clean['Inventory_Value_Difference'])
    / data_clean['Calculated_Inventory_Value']
) * 100

data_clean[
    data_clean['Inventory_Value_Diff_Pct'] > 5
][[
    'SKU_ID',
    'Quantity_On_Hand',
    'Unit_Cost_USD',
    'Total_Inventory_Value_USD',
    'Calculated_Inventory_Value',
    'Inventory_Value_Difference',
    'Inventory_Value_Diff_Pct'
]]

,SKU_ID,Quantity_On_Hand,Unit_Cost_USD,Total_Inventory_Value_USD,Calculated_Inventory_Value,Inventory_Value_Difference,Inventory_Value_Diff_Pct
8,SKU0009,1,1.33,1562.93,1.33,1561.60,117413.533835
19,SKU0020,1,1.00,1382.05,1.00,1381.05,138105.000000
56,SKU0057,1,1.49,1706.97,1.49,1705.48,114461.744966
120,SKU0121,1,3.17,3920.18,3.17,3917.01,123564.984227
150,SKU0151,1,7.34,8858.17,7.34,8850.83,120583.514986
156,SKU0157,1,5.50,6028.45,5.50,6022.95,109508.181818
322,SKU0323,2,4.38,6934.91,8.76,6926.15,79065.639269
333,SKU0334,1,1.36,1386.45,1.36,1385.09,101844.852941
336,SKU0337,1,1.36,1511.12,1.36,1509.76,111011.764706
337,SKU0338,1,2.19,2241.88,2.19,2239.69,102268.949772
387,SKU0388,1,0.31,311.89,0.31,311.58,100509.677419
428,SKU0429,1,3.54,3907.39,3.54,3903.85,110278.248588
455,SKU0456,1,2.00,2319.51,2.00,2317.51,115875.500000
457,SKU0458,1,2.29,2625.03,2.29,2622.74,114530.131004
493,SKU0494,1,0.41,425.78,0.41,425.37,103748.780488
527,SKU0528,1,1.76,1795.55,1.76,1793.79,101919.886364
533,SKU0534,1,3.52,4387.44,3.52,4383.92,124543.181818
574,SKU0575,1,3.16,4732.77,3.16,4729.61,149671.202532
622,SKU0623,1,4.54,4966.70,4.54,4962.16,109298.678414
699,SKU0700,1,3.75,4467.56,3.75,4463.81,119034.933333
731,SKU0732,1,4.86,4984.82,4.86,4979.96,102468.312757
734,SKU0735,1,4.39,5158.91,4.39,5154.52,117415.034169
747,SKU0748,1,1.00,1179.88,1.00,1178.88,117888.000000
761,SKU0762,1,4.12,4714.08,4.12,4709.96,114319.417476
798,SKU0799,1,0.44,530.97,0.44,530.53,120575.000000
911,SKU0912,1,7.14,7993.22,7.14,7986.08,111849.859944
913,SKU0914,1,2.06,2389.42,2.06,2387.36,115891.262136
968,SKU0969,2,7.05,11100.00,14.10,11085.90,78623.404255

In [ ]:
data_clean['Days_to_Expiry'] = (
    data_clean['Expiry_Date'] - pd.Timestamp('2025-08-15')
).dt.days

In [ ]:
data_clean[['Received_Date', 'Last_Purchase_Date', 'Expiry_Date', 'Audit_Date']].describe()

,Received_Date,Last_Purchase_Date,Expiry_Date,Audit_Date
count,1000,1000,1000,1000
mean,2025-06-09 11:00:57.600000256,2025-05-11 02:25:26.399999744,2026-12-31 19:35:02.400000,2025-07-26 05:44:09.600000
min,2025-03-13 00:00:00,2025-01-17 00:00:00,2025-03-17 00:00:00,2025-06-11 00:00:00
25%,2025-04-24 00:00:00,2025-03-28 00:00:00,2025-07-04 18:00:00,2025-07-04 00:00:00
50%,2025-06-06 00:00:00,2025-05-09 00:00:00,2026-05-01 00:00:00,2025-07-25 00:00:00
75%,2025-07-25 00:00:00,2025-06-26 00:00:00,2028-07-07 06:00:00,2025-08-19 00:00:00
max,2025-09-09 00:00:00,2025-09-08 00:00:00,2030-07-30 00:00:00,2025-09-09 00:00:00

In [ ]:
analysis_date = data_clean['Audit_Date'].max()

print("Analysis Date:", analysis_date)

Analysis Date: 2025-09-09 00:00:00

In [ ]:
data_clean['Days_to_Expiry'] = (
    data_clean['Expiry_Date'] - analysis_date
).dt.days

In [ ]:
data_clean[
    [
        'SKU_ID',
        'Expiry_Date',
        'Inventory_Status',
        'Days_to_Expiry'
    ]
].head(10)

    SKU_ID Expiry_Date Inventory_Status  Days_to_Expiry
0  SKU0001  2027-04-25         In Stock             593
1  SKU0002  2025-04-11        Low Stock            -151
2  SKU0003  2025-04-02    Expiring Soon            -160
3  SKU0004  2025-06-18    Expiring Soon             -83
4  SKU0005  2030-01-03         In Stock            1577
5  SKU0006  2027-12-25         In Stock             837
6  SKU0007  2025-04-12    Expiring Soon            -150
7  SKU0008  2025-04-02    Expiring Soon            -160
8  SKU0009  2025-07-30    Expiring Soon             -41
9  SKU0010  2025-05-01        Low Stock            -131

In [ ]:
print(
    "Already Expired:",
    (data_clean['Days_to_Expiry'] < 0).sum()
)

print(
    "Expiring within 30 days:",
    ((data_clean['Days_to_Expiry'] >= 0) &
     (data_clean['Days_to_Expiry'] <= 30)).sum()
)

Already Expired: 403
Expiring within 30 days: 26

In [ ]:
data_clean.drop(columns=['Days_to_Expiry'], inplace=True)

In [ ]:
pd.crosstab(
    data_clean['Inventory_Status'],
    data_clean['Expiry_Date'] < data_clean['Audit_Date']
)

col_0             False  True
Inventory_Status
Expiring Soon       101    228
In Stock            428      0
Low Stock           172     69
Out of Stock          2      0

In [ ]:
data_clean.groupby('Inventory_Status')['Days_of_Inventory'].agg(
    ['count', 'mean', 'min', 'max']
)

                  count       mean   min    max
Inventory_Status
Expiring Soon       329  10.768024  3.06  20.16
In Stock            428  10.986659  3.75  21.95
Low Stock           241   7.253693  0.33  16.82
Out of Stock          2   0.000000  0.00   0.00

In [ ]:
data_clean['Stock_Coverage_vs_LeadTime'] = (
    data_clean['Days_of_Inventory']
    - data_clean['Lead_Time_Days']
)

In [ ]:
data_clean[
    [
        'SKU_ID',
        'Days_of_Inventory',
        'Lead_Time_Days',
        'Stock_Coverage_vs_LeadTime'
    ]
].head(10)

    SKU_ID  Days_of_Inventory  Lead_Time_Days  Stock_Coverage_vs_LeadTime
0  SKU0001              12.57               1                       11.57
1  SKU0002               8.97              14                       -5.03
2  SKU0003              13.27               4                        9.27
3  SKU0004              11.02               4                        7.02
4  SKU0005              13.78               3                       10.78
5  SKU0006              13.59               7                        6.59
6  SKU0007               6.90               2                        4.90
7  SKU0008               6.22               2                        4.22
8  SKU0009              14.87               3                       11.87
9  SKU0010               6.78               7                       -0.22

In [ ]:
print(
    "SKUs below lead time:",
    (data_clean['Stock_Coverage_vs_LeadTime'] < 0).sum()
)

SKUs below lead time: 112

# REORDER RISK

In [ ]:
data_clean['Reorder_Gap'] = (
    data_clean['Quantity_On_Hand']
    - data_clean['Reorder_Point']
)

In [ ]:
data_clean['Reorder_Risk'] = (
    data_clean['Quantity_On_Hand']
    < data_clean['Reorder_Point']
)

In [ ]:
print(
    data_clean['Reorder_Risk'].value_counts()
)

Reorder_Risk
False    744
True     256
Name: count, dtype: int64

In [ ]:
print(
    "Reorder Risk %:",
    round(data_clean['Reorder_Risk'].mean() * 100, 2)
)

Reorder Risk %: 25.6

In [ ]:
data_clean[
    [
        'SKU_ID',
        'Quantity_On_Hand',
        'Reorder_Point',
        'Safety_Stock',
        'Reorder_Gap',
        'Reorder_Risk'
    ]
].head(10)

,SKU_ID,Quantity_On_Hand,Reorder_Point,Safety_Stock,Reorder_Gap,Reorder_Risk
0,SKU0001,359,51.0,22,308.0,False
1,SKU0002,314,744.0,254,-430.0,True
2,SKU0003,485,225.0,79,260.0,False
3,SKU0004,281,162.0,60,119.0,False
4,SKU0005,235,80.0,29,155.0,False
5,SKU0006,446,349.0,119,97.0,False
6,SKU0007,368,169.0,62,199.0,False
7,SKU0008,135,66.0,23,69.0,False
8,SKU0009,1,357.0,121,-356.0,True
9,SKU0010,49,85.0,34,-36.0,True

In [ ]:
data_clean['Safety_Stock_Gap'] = (
    data_clean['Quantity_On_Hand']
    - data_clean['Safety_Stock']
)

In [ ]:
data_clean['Safety_Stock_Risk'] = (
    data_clean['Quantity_On_Hand']
    < data_clean['Safety_Stock']
)

In [ ]:
print(data_clean['Safety_Stock_Risk'].value_counts())

print(
    "Safety Stock Risk %:",
    round(data_clean['Safety_Stock_Risk'].mean() * 100, 2)
)

Safety_Stock_Risk
False    937
True      63
Name: count, dtype: int64
Safety Stock Risk %: 6.3

In [ ]:
risk_summary = pd.DataFrame({
    'Risk_Metric': [
        'Reorder Risk',
        'Safety Stock Risk',
        'Below Lead Time Coverage'
    ],
    'SKU_Count': [
        data_clean['Reorder_Risk'].sum(),
        data_clean['Safety_Stock_Risk'].sum(),
        (data_clean['Stock_Coverage_vs_LeadTime'] < 0).sum()
    ]
})

risk_summary['Risk_Pct'] = (
    risk_summary['SKU_Count']
    / len(data_clean)
    * 100
).round(2)

risk_summary

                Risk_Metric  SKU_Count  Risk_Pct
0              Reorder Risk        256      25.6
1         Safety Stock Risk         63       6.3
2  Below Lead Time Coverage        112      11.2

In [ ]:
data_clean['Inventory_Risk_Score'] = (
    data_clean['Reorder_Risk'].astype(int)
    + data_clean['Safety_Stock_Risk'].astype(int)
    + (data_clean['Stock_Coverage_vs_LeadTime'] < 0).astype(int)
)

In [ ]:
risk_distribution = (
    data_clean['Inventory_Risk_Score']
    .value_counts()
    .sort_index()
    .reset_index()
)

risk_distribution.columns = ['Risk_Score', 'SKU_Count']

risk_distribution['Risk_Pct'] = (
    risk_distribution['SKU_Count']
    / len(data_clean)
    * 100
).round(2)

risk_distribution

   Risk_Score  SKU_Count  Risk_Pct
0           0        739      73.9
1           1        122      12.2
2           2        108      10.8
3           3         31       3.1

In [ ]:
pd.crosstab(
    data_clean['Inventory_Risk_Score'],
    data_clean['Inventory_Status']
)

Inventory_Status      Expiring Soon  In Stock  Low Stock  Out of Stock
Inventory_Risk_Score
0                               321       413          5             0
1                                 0         0        122             0
2                                 8        15         85             0
3                                 0         0         29             2

# SUPPLIERS

In [ ]:
data_clean['Supplier_Performance'] = pd.cut(
    data_clean['Supplier_OnTime_Pct'],
    bins=[0, 70, 85, 100],
    labels=['Poor', 'Average', 'Good'],
    include_lowest=True
)

In [ ]:
data_clean['Supplier_Performance'].value_counts()

Supplier_Performance
Average    511
Good       489
Poor         0
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    data_clean['Supplier_Performance'],
    data_clean['Inventory_Risk_Score']
)

Inventory_Risk_Score    0   1   2   3
Supplier_Performance
Average               389  60  47  15
Good                  350  62  61  16

In [ ]:
data_clean['Demand_Forecast_Accuracy_Pct'].describe()

count    1000.000000
mean       78.970810
std        11.065562
min        60.010000
25%        70.060000
50%        78.935000
75%        88.622500
max        97.960000
Name: Demand_Forecast_Accuracy_Pct, dtype: float64

In [ ]:
data_clean.groupby('Inventory_Risk_Score')[
    'Demand_Forecast_Accuracy_Pct'
].agg(['count', 'mean', 'median', 'min', 'max'])

                      count       mean  median    min    max
Inventory_Risk_Score
0                       739  79.540352  79.660  60.05  97.96
1                       122  76.813934  74.960  60.60  97.83
2                       108  77.133148  77.215  60.01  97.64
3                        31  80.284194  81.450  60.91  97.71

#EDA

In [ ]:
kpi = {
    'Total_SKUs': data_clean['SKU_ID'].nunique(),
    'Total_Inventory_Units': data_clean['Quantity_On_Hand'].sum(),
    'Total_Inventory_Value_USD': data_clean['Total_Inventory_Value_USD'].sum(),
    'Avg_Days_of_Inventory': data_clean['Days_of_Inventory'].mean(),
    'Low_Stock_SKUs': (
        data_clean['Inventory_Status'] == 'Low Stock'
    ).sum(),
    'Out_of_Stock_SKUs': (
        data_clean['Inventory_Status'] == 'Out of Stock'
    ).sum(),
    'Expiring_Soon_SKUs': (
        data_clean['Inventory_Status'] == 'Expiring Soon'
    ).sum(),
    'Negative_ATP_SKUs': (
        data_clean['Available_to_Promise'] < 0
    ).sum(),
    'Reorder_Risk_SKUs': data_clean['Reorder_Risk'].sum(),
    'Avg_Supplier_OnTime_Pct': (
        data_clean['Supplier_OnTime_Pct'].mean()
    ),
    'Avg_Forecast_Accuracy_Pct': (
        data_clean['Demand_Forecast_Accuracy_Pct'].mean()
    )
}

kpi

{'Total_SKUs': 1000,
 'Total_Inventory_Units': np.int64(231563),
 'Total_Inventory_Value_USD': np.float64(1259530.73),
 'Avg_Days_of_Inventory': np.float64(9.99311),
 'Low_Stock_SKUs': np.int64(241),
 'Out_of_Stock_SKUs': np.int64(2),
 'Expiring_Soon_SKUs': np.int64(329),
 'Negative_ATP_SKUs': np.int64(28),
 'Reorder_Risk_SKUs': np.int64(256),
 'Avg_Supplier_OnTime_Pct': np.float64(84.67189),
 'Avg_Forecast_Accuracy_Pct': np.float64(78.97081)}

In [ ]:
category_analysis = (
    data_clean
    .groupby('Category')
    .agg(
        SKUs=('SKU_ID', 'nunique'),
        Inventory_Units=('Quantity_On_Hand', 'sum'),
        Inventory_Value=('Total_Inventory_Value_USD', 'sum'),
        Avg_Days_Inventory=('Days_of_Inventory', 'mean'),
        Low_Stock_SKUs=('Reorder_Risk', 'sum'),
        Negative_ATP_SKUs=('Available_to_Promise', lambda x: (x < 0).sum())
    )
    .sort_values('Inventory_Value', ascending=False)
)

category_analysis

,SKUs,Inventory_Units,Inventory_Value,Avg_Days_Inventory,Low_Stock_SKUs,Negative_ATP_SKUs
Category,,,,,,
Beverages,120,41715,274510.21,10.040250,39,19
Personal Care,126,15706,204800.72,9.716508,35,0
Pantry,137,21666,171042.38,10.263504,40,0
Meat,87,19942,123089.22,10.218621,16,0
Household,103,11758,112561.53,10.254951,23,0
Seafood,66,10835,96149.99,10.583030,10,0
Frozen,86,21322,91377.01,9.672791,15,0
Dairy,96,27276,67616.42,9.225833,29,0
Fresh Produce,110,38342,59706.60,10.097455,32,5
Bakery,69,23001,58676.65,9.940290,17,4

In [ ]:
category_analysis['Inventory_Value_Pct'] = (
    category_analysis['Inventory_Value']
    / data_clean['Total_Inventory_Value_USD'].sum()
    * 100
).round(2)

category_analysis

,SKUs,Inventory_Units,Inventory_Value,Avg_Days_Inventory,Low_Stock_SKUs,Negative_ATP_SKUs,Inventory_Value_Pct
Category,,,,,,,
Beverages,120,41715,274510.21,10.040250,39,19,21.79
Personal Care,126,15706,204800.72,9.716508,35,0,16.26
Pantry,137,21666,171042.38,10.263504,40,0,13.58
Meat,87,19942,123089.22,10.218621,16,0,9.77
Household,103,11758,112561.53,10.254951,23,0,8.94
Seafood,66,10835,96149.99,10.583030,10,0,7.63
Frozen,86,21322,91377.01,9.672791,15,0,7.25
Dairy,96,27276,67616.42,9.225833,29,0,5.37
Fresh Produce,110,38342,59706.60,10.097455,32,5,4.74
Bakery,69,23001,58676.65,9.940290,17,4,4.66

In [ ]:
warehouse_analysis = (
    data_clean
    .groupby(['Warehouse_ID', 'Warehouse_Location'])
    .agg(
        SKUs=('SKU_ID', 'nunique'),
        Inventory_Units=('Quantity_On_Hand', 'sum'),
        Inventory_Value=('Total_Inventory_Value_USD', 'sum'),
        Avg_Days_Inventory=('Days_of_Inventory', 'mean'),
        Reorder_Risk_SKUs=('Reorder_Risk', 'sum'),
        Negative_ATP_SKUs=(
            'Available_to_Promise',
            lambda x: (x < 0).sum()
        )
    )
    .sort_values('Inventory_Value', ascending=False)
)

warehouse_analysis

,,SKUs,Inventory_Units,Inventory_Value,Avg_Days_Inventory,Reorder_Risk_SKUs,Negative_ATP_SKUs
Warehouse_ID,Warehouse_Location,,,,,,
WHSBY,Surabaya - Sidoarjo,198,44108,276105.20,10.046111,51,8
WHDPS,Denpasar - Tabanan,220,53212,275418.70,9.882318,60,5
WHBDG,Bandung - Rancaekek,220,47412,267190.76,9.852455,51,6
WHMDN,Medan - Deli Serdang,189,44224,235541.77,10.248995,42,6
WHJKT,Jakarta - Cengkareng,173,42607,205274.30,9.972659,52,3

In [ ]:
warehouse_analysis['Inventory_Value_Pct'] = (
    warehouse_analysis['Inventory_Value']
    / data_clean['Total_Inventory_Value_USD'].sum()
    * 100
).round(2)

warehouse_analysis

,,SKUs,Inventory_Units,Inventory_Value,Avg_Days_Inventory,Reorder_Risk_SKUs,Negative_ATP_SKUs,Inventory_Value_Pct
Warehouse_ID,Warehouse_Location,,,,,,,
WHSBY,Surabaya - Sidoarjo,198,44108,276105.20,10.046111,51,8,21.92
WHDPS,Denpasar - Tabanan,220,53212,275418.70,9.882318,60,5,21.87
WHBDG,Bandung - Rancaekek,220,47412,267190.76,9.852455,51,6,21.21
WHMDN,Medan - Deli Serdang,189,44224,235541.77,10.248995,42,6,18.70
WHJKT,Jakarta - Cengkareng,173,42607,205274.30,9.972659,52,3,16.30

In [ ]:
supplier_analysis = (
    data_clean
    .groupby('Supplier_Name')
    .agg(
        SKUs=('SKU_ID', 'nunique'),
        Inventory_Value=('Total_Inventory_Value_USD', 'sum'),
        Avg_OnTime=('Supplier_OnTime_Pct', 'mean'),
        Avg_Lead_Time=('Lead_Time_Days', 'mean'),
        Reorder_Risk=('Reorder_Risk', 'sum')
    )
    .sort_values('Avg_OnTime')
)

supplier_analysis

,SKUs,Inventory_Value,Avg_OnTime,Avg_Lead_Time,Reorder_Risk
Supplier_Name,,,,,
PT Prima Distribusi,89,116454.16,84.102022,3.550562,24
PT Segar Makmur,91,124320.10,84.128571,4.802198,33
PT DailyDairy,85,106290.16,84.140118,4.317647,23
PT Beverage Nusantara,104,117973.49,84.164712,3.673077,23
PT Nusantara Supplier,89,105332.86,84.168315,4.617978,23
PT Agro Raya,96,116169.41,84.636042,4.083333,28
PT Frozen Express,98,124407.75,84.712959,3.969388,26
PT Hygienic Supplies,110,135783.07,84.761909,3.718182,28
PT Bakerindo,113,161631.42,85.641239,3.946903,23
PT Indo Fresh,125,151168.31,85.655120,3.848000,25

In [ ]:
data_clean.to_csv(
    'supply_chain_inventory_clean.csv',
    index=False
)

In [ ]:
data_clean.to_excel(
    'supply_chain_inventory_clean.xlsx',
    index=False
)